module.exports = {
  SERVER_ERROR: 'サーバーエラーが発生しました',
  ROOM_NOT_FOUND: 'ルームが見つかりません',
  ROOM_ACCESS_DENIED: 'このルームにアクセスする権限がありません',
  ROOM_GROUP_ONLY: 'この操作はグループのみ対象です',
  USER_NOT_FOUND: 'ユーザーが見つかりません',
  MEMBER_NOT_FOUND: 'メンバーが見つかりません',
  MESSAGE_NOT_FOUND: 'メッセージが見つかりません',
  AUTH_TOKEN_REQUIRED: '認証トークンがありません',
  AUTH_TOKEN_INVALID: 'トークンが無効です',
  AUTH_INVALID_CREDENTIALS: 'ユーザーIDまたはパスワードが正しくありません',
  AUTH_REGISTER_REQUIRED: 'ユーザーID、表示名、パスワードは必須です',
  AUTH_DUPLICATE_LOGIN_ID: 'このユーザーIDは既に登録されています',
  AUTH_LOGIN_REQUIRED: 'ユーザーIDとパスワードは必須です',
  AUTH_PASSWORD_WRONG: '現在のパスワードが正しくありません',
  AUTH_PASSWORD_REQUIRED: '現在のパスワードと新しいパスワードは必須です',
  ADMIN_REQUIRED: '管理者権限が必要です',
  GROUP_ADMIN_REQUIRED: 'グループ管理者のみが実行できます',
  FILE_NOT_ATTACHED: 'ファイルが添付されていません',
  IMAGE_NOT_ATTACHED: '画像ファイルが添付されていません',
  VOICE_NOT_ATTACHED: '音声ファイルが添付されていません',
  FILE_TOO_LARGE: 'ファイルサイズが上限を超えています',
  NO_UPDATE_FIELDS: '更新する項目がありません',
  ALREADY_MEMBER: '既にメンバーです',
  SENDER_ONLY_DELETE: '自分のメッセージのみ削除できます',
  SENDER_ONLY_EDIT: '送信者のみ編集できます',
  EMOJI_REQUIRED: 'emoji は必須です',
  TEXT_REQUIRED: 'テキストは必須です',
  SELF_KICK_NOT_ALLOWED: '自分自身を除外することはできません。退会を使用してください。',
  LAST_ADMIN_CANNOT_LEAVE: 'あなたは最後のグループ管理者です。先に他のメンバーをグループ管理者に変更してください。',
};
