/**
 * E2E run report generator — markdown 出力 (#262)
 */

function escapeMd(s) {
  if (!s) return '';
  return s.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

function statusBadge(result) {
  if (result.fails.length > 0) return '❌ FAIL';
  if (result.warns.length > 0) return '⚠️ WARN';
  return '✅ PASS';
}

function generateReport(results) {
  const lines = [];
  const date = new Date().toISOString();
  const totalPass = results.filter(r => r.result.fails.length === 0).length;
  const totalFail = results.length - totalPass;
  const totalWarns = results.reduce((acc, r) => acc + r.result.warns.length, 0);

  lines.push(`# Light agent E2E run — ${date.slice(0, 19)} UTC`);
  lines.push('');
  lines.push(`**Source**: \`agent-server/tools/e2e/scenarios.json\``);
  lines.push(`**Issue**: [#262](https://github.com/gamasenninn/tealus/issues/262)`);
  lines.push('');

  lines.push('## Summary');
  lines.push('');
  lines.push(`| metric | value |`);
  lines.push(`|---|---|`);
  lines.push(`| Total scenarios | ${results.length} |`);
  lines.push(`| ✅ Pass | ${totalPass} |`);
  lines.push(`| ❌ Fail | ${totalFail} |`);
  lines.push(`| ⚠️ Warns | ${totalWarns} |`);
  lines.push('');

  lines.push('## Scenarios');
  lines.push('');
  lines.push('| id | status | latency | tokens (in/out) | tools called |');
  lines.push('|---|---|---|---|---|');
  for (const r of results) {
    const tools = (r.observed.tool_calls || []).map(t => t.tool).join(', ');
    const tu = r.observed.token_usage;
    const tokens = tu ? `${tu.input}/${tu.output}` : '—';
    const lat = r.observed.latency_ms ? `${r.observed.latency_ms}ms` : '—';
    lines.push(`| ${r.scenario.id} | ${statusBadge(r.result)} | ${lat} | ${tokens} | ${escapeMd(tools)} |`);
  }
  lines.push('');

  lines.push('## Details');
  lines.push('');
  for (const r of results) {
    lines.push(`### ${r.scenario.id} — ${statusBadge(r.result)}`);
    lines.push('');
    lines.push(`**Description**: ${r.scenario.description}`);
    lines.push('');
    lines.push(`**Prompt**: \`${r.scenario.prompt.slice(0, 200)}\``);
    lines.push('');
    lines.push(`**Target agent**: \`${r.scenario.target_agent}\``);
    lines.push('');

    if (r.observed.error) {
      lines.push('**Error**:');
      lines.push('```');
      lines.push(r.observed.error);
      lines.push('```');
      lines.push('');
    }

    if (r.result.fails.length > 0) {
      lines.push('**❌ Fails**:');
      for (const f of r.result.fails) lines.push(`- ${f}`);
      lines.push('');
    }
    if (r.result.warns.length > 0) {
      lines.push('**⚠️ Warns**:');
      for (const w of r.result.warns) lines.push(`- ${w}`);
      lines.push('');
    }

    lines.push(`**Tool chain observed**: ${(r.observed.tool_calls || []).map(t => `\`${t.tool}\``).join(' → ') || '(none)'}`);
    lines.push('');

    if (r.observed.token_usage) {
      lines.push(`**Tokens**: input=${r.observed.token_usage.input}, output=${r.observed.token_usage.output}`);
      lines.push('');
    }

    if (r.observed.latency_ms) {
      lines.push(`**Latency**: ${r.observed.latency_ms}ms`);
      lines.push('');
    }

    if (r.observed.bot_response_text) {
      const excerpt = r.observed.bot_response_text.length > 500
        ? r.observed.bot_response_text.slice(0, 500) + '... (truncated)'
        : r.observed.bot_response_text;
      lines.push('**Bot response (excerpt)**:');
      lines.push('```');
      lines.push(excerpt);
      lines.push('```');
      lines.push('');
    }

    if (r.observed.log_lines_found && r.observed.log_lines_found.length > 0) {
      lines.push(`**Expected log lines found**: ${r.observed.log_lines_found.map(l => `\`${l}\``).join(', ')}`);
      lines.push('');
    }

    if (r.scenario.manual_check) {
      lines.push('**Manual check** (人 review):');
      lines.push(`- [ ] ${r.scenario.manual_check}`);
      lines.push('');
    }
    lines.push('---');
    lines.push('');
  }

  lines.push('## Notes');
  lines.push('');
  lines.push('- 判定 layer: 決定論層 (fail) / 観察層 (warn) / 人 review 層 (manual_check の checkbox)');
  lines.push('- LLM の non-determinism を許容、絶対比較は避ける');
  lines.push('- regression check として fix の前後で run 比較を取る使い方');
  lines.push('');
  lines.push(`_Generated by \`agent-server/tools/e2e/run.js\` at ${date}_`);
  lines.push('');

  return lines.join('\n');
}

module.exports = { generateReport };
